# Generated by Django 5.0.6 on 2026-07-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Truck', 'Truck'), ('Minivan', 'Minivan'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Sports', 'Sports'), ('Electric', 'Electric')], default='Sedan', max_length=50),
        ),
    ]
