version: "3.8"
 
services:
  db:
    image: postgres:16
    container_name: car_dealership_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: car_dealership
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rajan22106
    ports:
      - "5432:5432"
    volumes:
      - car_dealership_pgdata:/var/lib/postgresql/data
 
volumes:
  car_dealership_pgdata: